export const TASKS = [
  {
    id: 1,
    name: "Task1",
    description: "Description1",
    status: "New Order",
    time: "8 hrs",
    days: "5 days left",
  },
  {
    id: 2,
    name: "Task2",
    description: "Description2",
    status: "InProgress",
    time: "6 hrs",
    days: "6 days left",
  },
  {
    id: 3,
    name: "Task3",
    description: "Description3",
    status: "Completed",
    time: "13 hrs",
    days: "4 days left",
  },
  {
    id: 4,
    name: "Task4",
    description: "Description4",
    status: "New Order",
    time: "22 hrs",
    days: "2 days left",
  },
  {
    id: 5,
    name: "Task5",
    description: "Description5",
    status: "InProgress",
    time: "2 hrs",
    days: "1 day left",
  },
  {
    id: 6,
    name: "Task6",
    description: "Description6",
    status: "Completed",
    time: "20 hrs",
    days: "11 days left",
  },
  {
    id: 7,
    name: "Task7",
    description: "Description7",
    status: "New Order",
    time: "2 hrs",
    days: "1 day left",
  },
];
